# Generated by Django 3.1.4 on 2020-12-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('author', models.CharField(max_length=30, null=True)),
                ('price', models.FloatField(null=True)),
                ('categorie', models.CharField(choices=[('Classic', 'Classic'), ('Comic', 'Comic'), ('Fantasi', 'Fantasi'), ('Herror', 'Herror')], max_length=30, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Delicered', 'Delicered'), ('Out of order', 'Out of order'), ('In Progress', 'In Progress')], max_length=200, null=True)),
            ],
        ),
    ]
